name: dji_thermal
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.13
  - numpy>=1.22.0
  - pillow>=9.0.0
  - tqdm>=4.65.0
  - pip>=23.0.0
  - pip:
    - pyexiv2>=2.11.0
    - piexif>=1.1.3

# 在别的电脑上创建环境的步骤：
# 1. 确保已安装 Anaconda 或 Miniconda
# 2. 打开终端或命令提示符
# 3. 转到存放 environment.yml 的目录
# 4. 执行命令: conda env create -f environment.yml
# 5. 等待环境创建完成
# 6. 激活环境: conda activate dji_thermal
#
# 注意：
# - 首次使用前需要确保 DJI Thermal SDK 已正确安装
# - Windows系统需要确保PowerShell可用（用于调用DJI SDK）
